Repository KangHayeonn/together-party-tonight-client, pull requests merged in 2023-08, with the labels that each got.

#100 [UPDATE] : 검색 상세 페이지 추가 기능 구현 & 코드 정리
  src/api/club.ts
  src/api/common/interceptors.ts
  src/api/search.ts
  src/app/login/page.tsx
  src/app/mypage/info/[id]/page.tsx
  src/app/redirect/page.tsx
  src/components/chat/ChatRoomFormBottom.tsx
  src/components/mypage/MemberModal.tsx
  src/components/mypage/ReviewDetailModal.tsx
  src/components/mypage/SideBar.tsx
  src/components/mypage/info/MyInfo.tsx
  src/components/search/map/KakaoMap.tsx
  src/components/search/mapType/SearchCategory.tsx
  src/components/search/mapType/SearchItemAside.tsx
  src/components/search/mapType/SearchItemDetail.tsx
  src/components/search/mapType/SearchItemSummary.tsx
  src/components/search/mapType/SearchOpenReviewBtn.tsx
  src/components/search/mapType/SearchOption.tsx
  src/components/search/mapType/SearchResult.tsx
  src/components/search/mapType/SearchReviewList.tsx
  src/components/search/mapType/SearchTagList.tsx
  src/components/write/ClubWriteTag.tsx
  src/components/write/ClubWriteTagPreview.tsx
  src/hooks/useSocket.tsx
  src/recoil/chat/chatState.ts
  src/styles/components/search/mapType/SearchItemSummary.tsx
  src/styles/components/search/mapType/SearchResult.tsx
  src/styles/components/search/mapType/SearchReviewList.tsx
  src/styles/components/write/ClubWriteTagPreview.tsx
  src/types/chat.ts
  src/types/review.ts
  src/utils/categoryFormat.ts
Labels: 🌈 update, ✋ code-review, ✨ add, 💄 add or update UI

#103 [ADD] : 알림 조회 api 기능 연동 & 로그인 후 안읽은 알림 개수 즉시 적용 이슈 해결
  src/api/alert.ts
  src/app/login/page.tsx
  src/components/alert/Alert.tsx
  src/components/chat/ChatRoomListAside.tsx
  src/components/layout/Header.tsx
  src/hooks/useSocket.tsx
  src/recoil/alert/alertState.ts
  src/styles/components/alert/Alert.tsx
  src/types/alert.ts
Labels: 🌈 update, ✋ code-review, 🐛 bug, ✨ add, 💄 add or update UI

#102 [ADD] : 공통 confirm modal 제작
  src/app/sample/page.tsx
  src/components/chat/ChatRoomFormTop.tsx
  src/components/common/ConfirmModal.tsx
  src/components/common/TextField.tsx
  src/components/common/modal/ConfirmModal.tsx
  src/components/common/modal/ModalForm.tsx
  src/components/search/mapType/SearchItemComment.tsx
  src/components/search/mapType/SearchItemSummary.tsx
  src/components/write/ClubWriteForm.tsx
  src/styles/components/common/modal/ConfirmModal.tsx
  src/styles/components/common/modal/ModalForm.tsx
Labels: 🌈 update, ✋ code-review, ✨ add, 💄 add or update UI

#105 [UPDATE] : 마이페이지 기능 추가/수정
  public/images/defaultPlusReview.svg
  src/api/mypage.ts
  src/app/layout.tsx
  src/app/mypage/info/[id]/page.tsx
  src/app/mypage/list/[category]/[id]/page.tsx
  src/app/redirect/page.tsx
  src/components/common/AuthLayout.tsx
  src/components/common/Modal.tsx
  src/components/layout/Header.tsx
  src/components/mypage/ApplyDetailModal.tsx
  src/components/mypage/MemberModal.tsx
  src/components/mypage/ReviewDetailModal.tsx
  src/components/mypage/SideBar.tsx
  src/styles/components/alert/Alert.tsx
  src/styles/components/mypage/ApplyDetailModal.tsx
  src/styles/components/mypage/ListItem.tsx
  src/styles/components/mypage/ReviewDetailModal.tsx
  src/styles/page/MyPage/MyInfo.tsx
Labels: 🌈 update, ✋ code-review, ✨ add, 💄 add or update UI

#106 [ADD] : 리스트형 검색페이지 & 리스트형 검색 상세페이지 API 연동 및 기능 구현
  src/components/common/DropDown.tsx
  src/components/common/RoundButton.tsx
  src/components/common/TextButton.tsx
  src/components/search/SearchTemplate.tsx
  src/components/search/listType/SearchCategory.tsx
  src/components/search/listType/SearchFilter.tsx
  src/components/search/listType/SearchItem.tsx
  src/components/search/listType/SearchItemBtn.tsx
  src/components/search/listType/SearchItemComment.tsx
  src/components/search/listType/SearchItemDetail.tsx
  src/components/search/listType/SearchItemSummary.tsx
  src/components/search/listType/SearchItemTagList.tsx
  src/components/search/listType/SearchList.tsx
  src/components/search/listType/SearchNav.tsx
  src/components/search/map/KakaoMapModal.tsx
  src/components/search/map/KakaoMapSingle.tsx
  src/components/search/mapType/SearchFilter.tsx
  src/components/search/mapType/SearchItemComment.tsx
  src/components/search/mapType/SearchItemSummary.tsx
  src/components/search/mapType/SearchTagList.tsx
  src/styles/components/common/SearchForm.tsx
  src/styles/components/common/SearchFormPreview.tsx
  src/styles/components/search/SearchTemplate.tsx
  src/styles/components/search/listType/SearchCategory.tsx
  src/styles/components/search/listType/SearchItemComment.tsx
  src/styles/components/search/listType/SearchList.tsx
  src/styles/components/search/listType/SearchTagList.tsx
  src/styles/components/search/map/KakaoModal.tsx
  src/styles/components/search/mapType/SearchTagList.tsx
Labels: 🌈 update, ✋ code-review, ✨ add, 💄 add or update UI

#98 [ADD] : 정산하기 api 연동
  public/images/off_close.svg
  src/api/mypage.ts
  src/app/mypage/layout.tsx
  src/app/mypage/list/[category]/[id]/page.tsx
  src/app/redirect/page.tsx
  src/components/common/DropDown.tsx
  src/components/mypage/ApplyDetailModal.tsx
  src/components/mypage/CalcAccountModal.tsx
  src/components/mypage/RequestCalcModal.tsx
  src/components/mypage/ReviewDetailModal.tsx
  src/components/mypage/list/MeetingItem.tsx
  src/constant/index.tsx
  src/recoil/modal/atom.ts
  src/recoil/mypage/atom.ts
  src/styles/components/mypage/CalcAccountModal.tsx
  src/styles/components/mypage/RequestCalcModal.tsx
  src/styles/page/MyPage/Meeting.tsx
  src/styles/page/MyPage/MyInfo.tsx
  src/types/mypage.ts
Labels: 🌈 update, ✋ code-review, ✨ add, 💄 add or update UI

#109 [ADD] : 맵형 검색페이지 > 무한스크롤 적용
  src/api/search.ts
  src/components/search/listType/SearchFilter.tsx
  src/components/search/mapType/SearchOption.tsx
  src/components/search/mapType/SearchResult.tsx
Labels: 🌈 update, ✋ code-review, 🐛 bug, ✨ add

#111 [UPDATE] : 정산탭 이슈 수정
  src/app/login/page.tsx
  src/app/redirect/page.tsx
  src/components/mypage/CalcAccountModal.tsx
  src/components/mypage/MemberModal.tsx
  src/components/mypage/info/EditInfo.tsx
  src/components/mypage/info/EditPwInfo.tsx
  src/components/mypage/info/MyReviewList.tsx
  src/components/mypage/list/MeetingItem.tsx
  src/styles/components/mypage/ApplyDetailModal.tsx
  src/styles/components/mypage/CalcAccountModal.tsx
  src/styles/components/mypage/ListItem.tsx
  src/styles/components/mypage/RequestCalcModal.tsx
  src/styles/components/mypage/ReviewDetailModal.tsx
  src/styles/components/mypage/SideBar.tsx
  src/styles/page/Login.tsx
  src/styles/page/Mail.tsx
  src/styles/page/MyPage/ListLayout.tsx
  src/styles/page/MyPage/Meeting.tsx
  src/styles/page/MyPage/MyInfo.tsx
  src/styles/page/sample.tsx
Labels: 🌈 update, ✋ code-review, 💄 add or update UI

#114 [ADD] 비밀번호 찾기 마크업, 기능구현
  src/api/login.ts
  src/app/find/page.tsx
  src/app/login/page.tsx
  src/app/mypage/info/[id]/page.tsx
  src/components/chat/ChatDefaultForm.tsx
  src/components/mypage/CalcAccountModal.tsx
  src/components/mypage/RequestCalcModal.tsx
  src/components/mypage/info/EditPwInfo.tsx
  src/styles/components/common/TextButton.tsx
  src/styles/components/mypage/ApplyDetailModal.tsx
  src/styles/components/mypage/ReviewDetailModal.tsx
Labels: 🌈 update, ✋ code-review, ✨ add

#115 [ADD] : 비밀번호 찾기 기능 구현
  src/api/login.ts
  src/app/find/page.tsx
  src/app/login/page.tsx
  src/app/mypage/info/[id]/page.tsx
  src/components/chat/ChatDefaultForm.tsx
  src/components/mypage/CalcAccountModal.tsx
  src/components/mypage/RequestCalcModal.tsx
  src/components/mypage/info/EditPwInfo.tsx
  src/styles/components/common/TextButton.tsx
  src/styles/components/mypage/ApplyDetailModal.tsx
  src/styles/components/mypage/ReviewDetailModal.tsx
Labels: 🌈 update, ✨ add, 💄 add or update UI
