Repository KangHayeonn/together-party-tonight-client, pull requests merged in 2023-07, with the labels that each got.

#81 [ADD] : 회원가입 기능구현
  public/images/emailFail.svg
  public/images/emailSuccess.svg
  src/api/index.ts
  src/api/login.ts
  src/app/login/page.tsx
  src/app/mypage/layout.tsx
  src/app/page.tsx
  src/app/redirect/page.tsx
  src/app/signup/page.tsx
  src/components/common/AuthLayout.tsx
  src/components/layout/Header.tsx
  src/hooks/useHandleInput.tsx
  src/styles/components/common/Loading.tsx
  src/styles/page/Login.tsx
Labels: 🌈 update, ✋ code-review, ✨ add

#76 [ADD] : 모임 만들기 기능 구현 및 API 연동
  package-lock.json
  package.json
  public/images/calendar.svg
  src/api/club.ts
  src/api/common/interceptors.ts
  src/api/index.ts
  src/api/search.ts
  src/app/sample/page.tsx
  src/components/common/Calendar.tsx
  src/components/common/DropDown.tsx
  src/components/common/NumberForm.tsx
  src/components/common/RoundButton.tsx
  src/components/common/SearchForm.tsx
  src/components/common/SearchFormPreview.tsx
  src/components/search/listType/SearchFilter.tsx
  src/components/search/mapType/SearchItemDetail.tsx
  src/components/search/mapType/SearchItemSummary.tsx
  src/components/search/mapType/SearchListAside.tsx
  src/components/search/mapType/SearchOption.tsx
  src/components/write/ClubWriteContent.tsx
  src/components/write/ClubWriteFilter.tsx
  src/components/write/ClubWriteForm.tsx
  src/components/write/ClubWriteImage.tsx
  src/components/write/ClubWriteTag.tsx
  src/components/write/ClubWriteTitle.tsx
  src/recoil/search/searchState.ts
  src/styles/components/common/Calendar.css
  src/styles/components/common/DropDown.tsx
  src/styles/components/common/SearchFormPreview.tsx
  src/styles/components/write/ClubWriteFilter.tsx
  src/styles/components/write/ClubWriteForm.tsx
  src/styles/components/write/ClubWriteImage.tsx
  src/styles/components/write/ClubWriteTag.tsx
  src/styles/components/write/ClubWriteTitle.tsx
  src/types/clubWrite.ts
  src/utils/dateFormat.ts
  src/utils/func/ClubWriteFunc.ts
  src/utils/mock/search.ts
  src/utils/tokenControl.ts
Labels: 🌈 update, ♻ refactor, ✋ code-review, ✨ add, 💄 add or update UI

#66 [ADD] : map형 검색페이지 api 연동
  public/images/category/exercisePin.png
  public/images/category/foodPin.png
  public/images/category/hobbyPin.png
  public/images/category/playPin.png
  public/images/category/studyPin.png
  public/images/category/travelPin.png
  public/images/category/volunterrPin.png
  src/api/index.ts
  src/api/search.ts
  src/api/test.ts
  src/app/api/exmaple/route.ts
  src/app/sample/page.tsx
  src/components/chat/ChatMessageList.tsx
  src/components/common/CheckBox.tsx
  src/components/common/NumberForm.tsx
  src/components/common/SearchForm.tsx
  src/components/common/SliderForm.tsx
  src/components/search/listType/SearchFilter.tsx
  src/components/search/map/KakaoMap.tsx
  src/components/search/mapType/SearchCategory.tsx
  src/components/search/mapType/SearchFilter.tsx
  src/components/search/mapType/SearchListAside.tsx
  src/components/search/mapType/SearchOption.tsx
  src/components/search/mapType/SearchResult.tsx
  src/components/search/mapType/SearchStatus.tsx
  src/components/search/mapType/SearchTagList.tsx
  src/components/write/ClubWriteFilter.tsx
  src/recoil/search/searchState.ts
  src/styles/components/common/SearchForm.tsx
  src/styles/components/search/mapType/SearchResult.tsx
  src/types/search.ts
  src/utils/categoryFormat.ts
  src/utils/func/SearchFunc.ts
Labels: 🌈 update, ♻ refactor, ✋ code-review, ✨ add, 💄 add or update UI

#89 [ADD] 마이페이지 기능구현 -wip
  next.config.js
  public/images/Account.svg
  src/api/mypage.ts
  src/app/mypage/info/[id]/page.tsx
  src/app/mypage/info/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/list/[category]/[id]/page.tsx
  src/app/mypage/list/[category]/layout.tsx
  src/app/mypage/list/[category]/page.tsx
  src/app/redirect/page.tsx
  src/app/signup/page.tsx
  src/components/common/AuthLayout.tsx
  src/components/common/Modal.tsx
  src/components/common/TextButton.tsx
  src/components/common/TextField.tsx
  src/components/layout/Header.tsx
  src/components/mypage/ApplyDetailModal.tsx
  src/components/mypage/DetailModal.tsx
  src/components/mypage/ReviewDetailModal.tsx
  src/components/mypage/SideBar.tsx
  src/components/mypage/info/EditInfo.tsx
  src/components/mypage/info/EditPwInfo.tsx
  src/components/mypage/info/MyInfo.tsx
  src/components/mypage/info/MyRating.tsx
  src/components/mypage/info/MyReviewList.tsx
  src/components/mypage/list/MeetingItem.tsx
  src/components/mypage/list/ReviewItem.tsx
  src/constant/index.tsx
  src/hooks/useHandleInput.tsx
  src/recoil/modal/atom.ts
  src/styles/components/common/Modal.tsx
  src/styles/components/mypage/ApplyDetailModal.tsx
  src/styles/components/mypage/ReviewDetailModal.tsx
  src/styles/page/MyPage/MyInfo.tsx
  src/types/mypage.ts
Labels: 🌈 update, ✋ code-review, ✨ add, 💄 add or update UI

#93 [ADD] : 댓글 기능 구현
  src/api/comment.ts
  src/app/login/page.tsx
  src/app/sample/page.tsx
  src/components/chat/ChatDefaultForm.tsx
  src/components/common/TextField.tsx
  src/components/layout/Header.tsx
  src/components/search/map/KakaoMapSingle.tsx
  src/components/search/mapType/SearchItemAside.tsx
  src/components/search/mapType/SearchItemComment.tsx
  src/components/search/mapType/SearchListAside.tsx
  src/hooks/useSocket.tsx
  src/recoil/comment/commentState.ts
  src/recoil/socket/socketState.ts
  src/styles/components/search/mapType/SearchItemComment.tsx
  src/types/comment.ts
  src/types/socket.ts
  src/utils/socket.ts
Labels: 🌈 update, ✋ code-review, 🐛 bug, ✨ add, 💄 add or update UI

#94 [BUGFIX] : 초기 진입시 Kakao Map API load 안되는 이슈 해결
  src/components/chat/ChatMessageList.tsx
  src/components/search/map/KakaoMap.tsx
  src/components/search/mapType/SearchItemAside.tsx
  src/components/search/mapType/SearchOpenReviewBtn.tsx
  src/components/search/mapType/SearchReviewList.tsx
Labels: 🌈 update, ✋ code-review, 🐛 bug

#95 [ADD] : 채팅하기 기능 API & 소켓 연동
  src/api/chat.ts
  src/api/club.ts
  src/api/common/interceptors.ts
  src/api/login.ts
  src/app/login/page.tsx
  src/components/chat/ChatDefaultForm.tsx
  src/components/chat/ChatMessageList.tsx
  src/components/chat/ChatRoomFormBottom.tsx
  src/components/chat/ChatRoomFormTop.tsx
  src/components/chat/ChatRoomListAside.tsx
  src/components/layout/Header.tsx
  src/components/search/mapType/SearchItemComment.tsx
  src/components/search/mapType/SearchItemDetail.tsx
  src/components/search/mapType/SearchItemSummary.tsx
  src/hooks/useSocket.tsx
  src/recoil/socket/socketState.ts
  src/styles/components/chat/ChatRoomListAside.tsx
  src/types/chat.ts
  src/types/socket.ts
  src/utils/dateFormat.ts
Labels: 🌈 update, ✋ code-review, ✨ add
